export const toDoList = [
    { id: 1,
      title: "Grocery Shopping",
      description: "Buy groceries for the week, including fruits, vegetables, dairy, and snacks.",
      date: "2024-07-20",
      tag: "Home",
    },
    { id: 2,
      title: "Client Meeting",
      description: "Discuss project Zoom.",
      date: "2024-07-21",
      tag: "Business",
    },
    { id: 3,
      title: "Yoga Class",
      description: "Attend a one-hour yoga class at the local studio.",
      date: "2024-07-22",
      tag: "Personal",
    },
    { id: 4,
      title: "Team Presentation",
      description: "Prepare and present the quarterly results to the team.",
      date: "2024-07-23",
      tag: "Business",
    },
    { id: 5,
      title: "Gardening",
      description: "Plant new flowers and trim the bushes in the garhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhden..ygggggggggggggggggiuyi7tttttttttrrrrrrrrvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
      date: "2024-07-24",
      tag: "Home",
    },
    { id: 6,
      title: "Doctor's Appointment",
      description: "Annual check-up appointment with Dr. Smith.",
      date: "2024-07-25",
      tag: "Personal",
    },
    { id: 7,
      title: "Website Redesign",
      description: "Work on redesigning the homepage of the company website.",
      date: "2024-07-26",
      tag: "Business",
    },
    { id: 8,
      title: "Family Dinner",
      description: "Prepare a special dinner for the family gathering.",
      date: "2024-07-27",
      tag: "Home",
    },
    { id: 9,
      title: "Book Reading",
      description: "Finish reading 'The Great Gatsby' and write a summary.",
      date: "2024-07-28",
      tag: "Personal",
    },
    { id: 10,
      title: "Budget Review",
      description: "Review the monthly budget and adjust for any overspending.",
      date: "2024-07-29",
      tag: "Business",
    },
  ];
  
  